### ISSUE TITLE
好像没有点击事件，列表点击波纹也没有，也没有列表分割线

### ISSUE THREAD

**Issue by atjiu** [TakWolf/Android-HeaderAndFooterRecyclerView#1]
翻了下源码，没找到点击事件

就像listview原生自带的列表波纹，这个也没找到

看了下你是用padding来分割的列表，如果把padding去掉，就没有效果了
![qq 20170612103223](https://user-images.githubusercontent.com/6915570/27017357-74797d5c-4f5a-11e7-8ec7-f367c13d7ff1.png)

不知道大大有没有想法把这些加上

PS: 我之前折腾过一点recyclerview组件，写了一篇博客，大大可以看看 https://tomoya92.github.io/2017/04/10/android-recyclerview-adapter/#%E5%88%97%E8%A1%A8%E5%88%86%E5%89%B2%E7%BA%BF 能加进来就更好了 :joy:

**Comment by TakWolf** [comment]
这个只想扩展HeaderView和FooterView， 不打算提供其他功能。上面这几个功能感觉不需要单独封装吧。

点击波纹最简单的实现：android:background="?attr/selectableItemBackground"
分割线是基于  RecyclerView.ItemDecoration 吧，这个可以单独封装，没必要放到一起吧。

**Comment by TakWolf** [comment]
关于点击事件，  OnItemClickListener  这个封装是不合理的。我个人的观点。
如果使用ListView，我也会禁用掉默认的点击效果自己配置。理由如下：

1. 如果全局提供配置，默认情况是整个item具有点击效果，并且整个item有涟漪效果。但是如果我的布局样式是这样的，我并不需要整个item都有点击效果，只需要卡片控件有点击效果
![screenshot_2017-06-12-11-04-30](https://user-images.githubusercontent.com/6064962/27018130-8cb8b896-4f60-11e7-8482-ad49ebbaded8.png)
 
2. 整个item点击也不具有通用性，很多情况下，需求并不需要整个item有点击效果，而是希望上面的若干按钮有点击效果，反而两者事件会冲突，例如：
![screenshot_2017-06-12-11-20-15](https://user-images.githubusercontent.com/6064962/27018252-84eb8912-4f61-11e7-8772-5b7bbc27ea69.png)
上面有两个按钮需要点击，但是全局并不需要点击。


我自己觉得更合理的方式是，在ViewHolder中按需配置点击事件：
```
class ViewHolder extends RecyclerView.ViewHolder {

        ViewHolder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);
        }

        @OnClick(R.id.btn_item)
        void onBtnItemClick() {
            // 处理点击
        }

        @OnLongClick(R.id.btn_item)
        boolean onBtnItemLongClick() {
           // 处理长按
        }
}
```
这种写法并不复杂，也可以将Adapter相关的逻辑封装到adapter自身中，也不需要额外的封装。

RecyclerView没有提供类似ListView的OnItemClickListener  接口，也是因为开发组觉得没必要。
可以参考这个：https://stackoverflow.com/questions/24885223/why-doesnt-recyclerview-have-onitemclicklistener

**Comment by atjiu** [comment]
不过我还是觉得集成进去比较好，用到列表基本就那些东西，至少点击事件加一个，这样不用用户自己再处理了，直接实现就可以了，这样比较方便

**Comment by TakWolf** [comment]
@tomoya92 
这个封装只扩展了recyclerView，没涉及adapter，假如你想要实现 OnItemClickListener （通过Adapter实现），用户之前的业务Adapter可以完全原封不动的使用。

**Comment by atjiu** [comment]
@TakWolf 嗯，明白了 :smile:
